echo "\e[1;30m This is black text \e[0m"
echo "\e[1;31m This is red text \e[0m"
echo "\e[1;32m This is green text \e[0m"
echo "\e[1;33m This is yellow text \e[0m"
echo "\e[1;34m This is blue text \e[0m"
echo "\e[1;35m This is red text \e[0m"
echo "\e[1;36m This is red text \e[0m"
echo "\e[1;37m This is white text \e[0m"
echo "test backgroud color"
echo "\e[1;40m This is black text \e[0m"
echo "\e[1;41m This is red text \e[0m"
echo "\e[1;42m This is green text \e[0m"
echo "\e[1;43m This is yellow text \e[0m"
echo "\e[1;44m This is blue text \e[0m"
echo "\e[1;45m This is red text \e[0m"
echo "\e[1;46m This is red text \e[0m"
echo "\e[1;47m This is white text \e[0m"
